-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "features" SET NOT NULL,
ALTER COLUMN "features" SET DATA TYPE TEXT,
ALTER COLUMN "payAsYouGo" SET NOT NULL,
ALTER COLUMN "payAsYouGo" SET DATA TYPE TEXT;
