import { Directories } from "@prisma/client";
import * as z from "zod";

export const validateDirectories: z.ZodType<Directories> = z.lazy(() =>
  z.object({
    id: z.string(),
    createdAt: z.date(),
    updatedAt: z.date(),
    websiteUrl: z.string(),
    twitterUrl: z.string(),
    facebookUrl: z.string(),
    instagramUrl: z.string(),
    amazonMusicUrl: z.string(),
    youtubeUrl: z.string(),
    spotifyUrl: z.string(),
    applePodcastsUrl: z.string(),
    googlePodcastsUrl: z.string(),
    stitcherUrl: z.string(),
    tuneinUrl: z.string(),
    pocketCastsUrl: z.string(),
    overcastUrl: z.string(),
    castroUrl: z.string(),
    castboxUrl: z.string(),
    podchaserUrl: z.string(),
    deezerUrl: z.string(),
    podfriendUrl: z.string(),
    podcastAddictUrl: z.string(),
    breakerUrl: z.string(),
    radiopublicUrl: z.string(),
    podcastId: z.string(),
  }),
);

export const defaultDirectoriesValue: Directories = {
  id: "",
  createdAt: new Date(),
  updatedAt: new Date(),
  websiteUrl: "",
  amazonMusicUrl: "",
  twitterUrl: "",
  facebookUrl: "",
  instagramUrl: "",
  youtubeUrl: "",
  spotifyUrl: "",
  applePodcastsUrl: "",
  googlePodcastsUrl: "",
  stitcherUrl: "",
  tuneinUrl: "",
  pocketCastsUrl: "",
  overcastUrl: "",
  castroUrl: "",
  castboxUrl: "",
  podchaserUrl: "",
  deezerUrl: "",
  podfriendUrl: "",
  podcastAddictUrl: "",
  breakerUrl: "",
  radiopublicUrl: "",
  podcastId: "",
};
